--- #YAML:1.0
name: Spork-Template-Mason
version: 0.03
author:
  - Dave Rolsky <autarch@urth.org>
abstract: Spork templating with Mason
license: perl
requires:
  Spoon::Template::Mason: 0.01
provides:
  Spork::Template::Mason:
    file: lib/Spork/Template/Mason.pm
    version: 0.03
generated_by: Module::Build version 0.23
